const vokabeln = {
    "Hallo": "Привіт",
    "Welt": "Світ",
    "Haus": "Будинок",
    "Auto": "Автомобіль",
    "Katze": "Кіт",
    "Hund": "Собака",
    "Apfel": "Яблуко",
    "Tisch": "Стіл",
    "Stuhl": "Стілець",
    "Blume": "Квітка",
    "Sonne": "Сонце",
    "Mond": "Місяць",
    "Wasser": "Вода",
    "Essen": "Їжа",
    "Trinken": "Пити",
    "Buch": "Книга",
    "Schule": "Школа",
    "Universität": "Університет",
    "Computer": "Комп'ютер",
    "Musik": "Музика",
    "Liebe": "Любов",
    "Du": "Ти",
    "Er/Sie/Es": "Він/Вона/Воно",
    "Wir": "Ми",
    "Ihr": "Ви",
    "Sie (Plural)": "Вони",
    "Ja": "Так",
    "Nein": "Ні",
    "Vielleicht": "Можливо",
    "Warum": "Чому",
    "Wann": "Коли",
    "Wo": "Де",
    "Wie": "Як",
    "Was": "Що",
    "Gut": "Добре",
    "Schlecht": "Погано",
    "Richtig": "Правильно",
    "Falsch": "Неправильно",
    "Bitte": "Будь ласка",
    "Danke": "Дякую",
    "Entschuldigung": "Вибачте",
    "Ich verstehe nicht": "Я не розумію",
    "Wie geht es dir?": "Як справи?",
    "Mir geht es gut.": "Мені добре.",
    "Was ist dein Name?": "Як тебе звуть?",
    "Mein Name ist": "Мене звуть",
    "Ich liebe dich": "Я тебе люблю",
    "Warum": "Чому",
    "Wann": "Коли",
    "Welcher": "Який",
    "Welche": "Яка",
    "Welches": "Яке",
    "Ich": "Я",
    "Du": "Ти",
    "Er": "Він",
    "Sie (singular)": "Вона",
    "Es": "Воно",
    "Wir": "Ми",
    "Ihr": "Ви",
    "Sie (plural)": "Вони",
    "Mein": "Мій",
    "Dein": "Твій",
    "Sein": "Його",
    "Ihr (singular)": "Її",
    "Unser": "Наш",
    "Euer": "Ваш",
    "Ihr (plural)": "їхній",
    "Ihr (formal)": "Ваш",
    "Diese": "Цей",
    "Dieser": "Ця",
    "Dieses": "Це",
    "Jener": "Той",
    "Jene": "Та",
    "Jenes": "Те",
    "Hier": "Тут",
    "Dort": "Там",
    "Da": "Ось",
    "Jetzt": "Зараз",
    "Später": "Пізніше",
    "Gestern": "Вчора",
    "Heute": "Сьогодні",
    "Morgen": "Завтра",
    "Sehr": "Дуже",
    "Wenig": "Мало",
    "Viel": "Багато",
    "Mehr": "Більше",
    "Weniger": "Менше",
    "Gut": "Добре",
    "Schlecht": "Погано",
    "Groß": "Великий",
    "Klein": "Малий",
    "Alt": "Старий",
    "Jung": "Молодий",
    "Neu": "Новий",
    "Alt (Zeitalter)": "Давній",
    "Neu (Zeitalter)": "Сучасний",
    "Hoch": "Високий",
    "Niedrig": "Низький",
    "Lang": "Довгий",
    "Kurz": "Короткий",
    "Breit": "Широкий",
    "Eng": "Вузький",
    "Dünn": "Тонкий",
    "Dick": "Товстий",
    "Gesund": "Здоровий",
    "Krank": "Хворий",
    "Glücklich": "Щасливий",
    "Traurig": "Сумний",
    "Hungrig": "Голодний",
    "Durstig": "Спраглий",
    "Müde": "Втомлений",
    "Wach": "Прокинутий",
    "Schnell": "Швидко",
    "Langsam": "Повільно",
    "Bald": "Скоро",
    "Spät": "Пізно",
    "Früh": "Рано",
    "Richtig": "Правильно",
    "Falsch": "Неправильно",
    "Nahe": "Близько",
    "Weit": "Далеко",
    "Links": "Зліва",
    "Rechts": "Справа",
    "Oben": "Зверху",
    "Unten": "Знизу",
    "Innen": "Усередині",
    "Außen": "Ззовні",
    "Heiß": "Гарячий",
    "Kalt": "Холодний",
    "Hell": "Світлий",
    "Dunkel": "Темний",
    "Laut": "Голосний",
    "Leise": "Тихий",
    "Alt (Zeit)": "Старий (час)",
    "Neu (Zeit)": "Новий (час)",
    "Tag": "День",
    "Nacht": "Ніч",
    "Morgen": "Ранок",
    "Abend": "Вечір",
    "Woche": "Тиждень",
    "Monat": "Місяць",
    "Jahr": "Рік",
    "Minute": "Хвилина",
    "Stunde": "Година",
    "Tag (Kalender)": "День (календар)",
    "Woche": "Тиждень",
    "Monat": "Місяць",
    "Jahr": "Рік",
    "Heute": "Сьогодні",
    "Morgen": "Завтра",
    "Gestern": "Вчора",
    "Montag": "Понеділок",
    "Dienstag": "Вівторок",
    "Mittwoch": "Середа",
    "Donnerstag": "Четвер",
    "Freitag": "П'ятниця",
    "Samstag": "Субота",
    "Sonntag": "Неділя",
    "Frühling": "Весна",
    "Sommer": "Літо",
    "Herbst": "Осінь",
    "Winter": "Зима",
    "Wasser": "Вода",
    "Feuer": "Вогонь",
    "Luft": "Повітря",
    "Erde": "Земля",
    "Himmel": "Небо",
    "Sonne": "Сонце",
    "Mond": "Місяць",
    "Stern": "Зірка",
    "Wolke": "Хмара",
    "Regen": "Дощ",
    "Schnee": "Сніг",
    "Wind": "Вітер",
    "Hitze": "Спека",
    "Kälte": "Холод",
    "Frühling": "Весна",
    "Sommer": "Літо",
    "Herbst": "Осінь",
    "Winter": "Зима",
    "Blume": "Квітка",
    "Baum": "Дерево",
    "Wald": "Ліс",
    "Fluss": "Ріка",
    "See": "Озеро",
    "Berg": "Гора",
    "Tal": "Долина",
    "Strand": "Пляж",
    "Meer": "Море",
    "Ozean": "Океан",
    "Insel": "Острів",
    "Wüste": "Пустеля",
    "Stadt": "Місто",
    "Dorf": "Село",
    "Land": "Країна",
    "Haus": "Будинок",
    "Wohnung": "Квартира",
    "Zimmer": "Кімната",
    "Familie": "Сім'я",
    "Eltern": "Батьки",
    "Mutter": "Мати",
    "Vater": "Батько",
    "Kinder": "Діти",
    "Sohn": "Син",
    "Tochter": "Донька",
    "Großeltern": "Дідусь та Бабуся",
    "Großvater": "Дідусь",
    "Großmutter": "Бабуся",
    "Geschwister": "Брати та Сестри",
    "Bruder": "Брат",
    "Schwester": "Сестра",
    "Verwandte": "Родичі",
    "Onkel": "Дядько",
    "Tante": "Тітка",
    "Cousin": "Кузен",
    "Cousine": "Кузина",
    "Ehemann": "Чоловік",
    "Ehefrau": "Дружина"
    // Fügen Sie weitere Vokabeln hinzu
};

function uebersetzen() {
    const deutschWort = document.getElementById("deutschInput").value;
    const ukrainischOutput = document.getElementById("ukrainischOutput");

    if (vokabeln.hasOwnProperty(deutschWort)) {
        const ukrainischWort = vokabeln[deutschWort];
        ukrainischOutput.textContent = `Übersetzung auf Ukrainisch: ${ukrainischWort}`;
    } else {
        ukrainischOutput.textContent = "Übersetzung nicht gefunden";
    }
}